### ISSUE TITLE
scene.pointerY - throws Format Exception

### ISSUE THREAD

**Issue by sebestyn168** [canhorn/EventHorizon.Blazor.Interop#32]
I'm not sure if the problem comes from EventHorizon or BabylonJS itself.
scene.pointerX seems to work (but actually returns an integer instead of decimal)
scene.pointerY throw a Format Exception (although checking the string representation gives a proper decimal).

I get the values as string to check
```
var x_ = EventHorizon.Blazor.Interop.EventHorizonBlazorInterop.Get<string>(scene.___guid, "pointerX");
var x = scene.pointerX;
var y_ = EventHorizon.Blazor.Interop.EventHorizonBlazorInterop.Get<string>(scene.___guid, "pointerY");
var y = scene.pointerY;
```

x_ = '58'
y_ = '251.40625'

![image](https://user-images.githubusercontent.com/15944564/132827637-658bee07-6745-46df-bac3-6a83cde3335d.png)

**Comment by canhorn** [comment]
This might be a problem with the with the data passing between the two layers. 

But I was not able to replicate this with the Edge browser and .NET5/6.

Is it happening without being in Debug?
Which version of .NET is the browser using?
And which browser was this tested in?

**Comment by sebestyn168** [comment]
It happens both in Debug and Release.
I'm using .Net 5
I tried with
- Chrome - latest Version 93.0.4577.63 (Build officiel) (64 bits)
- Firefox - latest Version 92.0 (64 bits)
- Edge - latest Version 93.0.961.47 (Version officielle) (64 bits)
I don't know how to check the .net version in the browser though.

On my machine, downloading the repos and running EventHorizon.Blazor.Interop.Sample allows to reproduce the error when testing both "Interop Get Decimal Test" and "Interop Get Float Test"
![image](https://user-images.githubusercontent.com/15944564/133077846-f2a1fea3-a62e-4707-b18c-3e15316375e3.png)
![image](https://user-images.githubusercontent.com/15944564/133077974-e764ea0d-0459-4df5-bdf3-e4f0a7e7b580.png)

Again, by retrieving the string value, it seems the data is correct and thus the problem would stand in the format conversion (an other error being the rounding of scene.pointerX - allowing the conversion to work)
```
    public decimal RunTest()
    {
        var test = EventHorizonBlazorInterop.Get<string>(
            "getPrimitive",
            "numberResult"
        );
        return EventHorizonBlazorInterop.Get<decimal>(
        "getPrimitive",
        "numberResult"
    );
```
![image](https://user-images.githubusercontent.com/15944564/133077230-b0e5a917-fbdf-4ea6-b07a-31b19784cf46.png)

**Comment by canhorn** [comment]
Thank you for that information!

Can you also check the tests on this site: https://polite-plant-0f8750a10.azurestaticapps.net/

That is the Sample deployed as a static site and currently works on my phones browser.

I will looking into the dotnet sdk versions for issues.

Also in `EventHorizonBlazorInterop.Get` there is a spot where it will return the value as a string before it converts it, you should be able to breakpoint there and see the value.

**Comment by sebestyn168** [comment]
spoiler I found the problem ^^ - well half of the problem :{
Thank you for your investigation, I really appreciate it!

I tried your site on my machine, my iPhone and even a remote server and I always get the same error

As you suggested, I debuged `EventHorizonBlazorInterop.Get`  to check what could possibly go wrong
![image](https://user-images.githubusercontent.com/15944564/133121670-c60bb727-a6d6-423b-94e4-cbd01415d15e.png)

That's when i got the illumination - `culture`!
just add the culture to the convert and it works...
```
                return (T)Convert.ChangeType(
                    result,
                    uType,
                    CultureInfo.InvariantCulture
                );
```

Now, it's not too much of an issue in my application, but I wonder why `scene.pointerX` has an `integer` representation?

**Comment by canhorn** [comment]
Awesome! I will get a fix to force the InvariantCulture!

For an integer on scene.pointerX, I think that is because of how pixels can be a decimal or integer based on screen settings like resolution and DPI. But that is on BabylonJS giving that value.
